;完善好配置文件后，请将config_example.ini改为config.ini

[Openai]
openai_api_key  = sk-

[Azureopenai]
openai_api_base = https://wjxsouthus2.openai.azure.com/
openai_api_key = 5f13abd9a42b4147a08515bb3fe08e6b
gpt35_deployment_name = gpt35

[AzureSpeech]
AZURE_API_KEY = 6f84e396e83344eaac57a520ae82fff9
AZURE_REGION = eastasia

[Snowboy]
Snowboy_Model_Path = snowboy/resources/models/Yoyo.pmdl
Sensitivity = 0.6