;完善好配置文件后，请将config_example.ini改为config.ini

[Openai]
openai_api_key  = sk-

[Azureopenai]
openai_api_base = 
openai_api_key = 
gpt35_deployment_name = 

[AzureSpeech]
AZURE_API_KEY = 
AZURE_REGION = 

[Snowboy]
Snowboy_Model_Path = 
Sensitivity = 0.6